[theme]
base = "light"

[api]
OpenAI_Secret_Key= "sk-proj-lsXZJhc0PyFXYbSytgpBT3BlbkFJjGaMbfFj32PKeqK8utKz"

[credentials]
streamlit_username = "jadeids2023@gmail.com"
streamlit_password = "Genaiids@2023"

snowflake_user = "umesh5511"
snowflake_password = "Umesh5511"
snowflake_account ="WNMQTAN-WR06094"